// Mocked data for Kachankawal Rural Municipality App

export const MUNICIPALITY_INFO = {
  name: 'Kachankawal Rural Municipality',
  nepaliName: 'कचनकवल गाउँपालिका',
  district: 'Jhapa District, Province No. 1',
  established: '2017',
  area: '94.95 sq. km',
  population: '~28,000',
  wards: 7,
  website: 'kachankawal.gov.np',
  phone: '+977-023-XXXXXX',
  email: 'info@kachankawal.gov.np',
  address: 'Kachankawal, Jhapa, Nepal',
};

export const ELECTED_REPRESENTATIVES = [
  {
    id: '1',
    name: 'Ram Prasad Sharma',
    position: 'Chairperson',
    ward: 'All Wards',
    phone: '+977-9800000001',
    avatar: 'https://i.pravatar.cc/150?img=11',
  },
  {
    id: '2',
    name: 'Sita Devi Rai',
    position: 'Vice-Chairperson',
    ward: 'All Wards',
    phone: '+977-9800000002',
    avatar: 'https://i.pravatar.cc/150?img=20',
  },
  {
    id: '3',
    name: 'Hari Bahadur Limbu',
    position: 'Ward Chairperson',
    ward: 'Ward 1',
    phone: '+977-9800000003',
    avatar: 'https://i.pravatar.cc/150?img=13',
  },
  {
    id: '4',
    name: 'Maya Gurung',
    position: 'Ward Chairperson',
    ward: 'Ward 2',
    phone: '+977-9800000004',
    avatar: 'https://i.pravatar.cc/150?img=21',
  },
  {
    id: '5',
    name: 'Bikash Thapa',
    position: 'Ward Chairperson',
    ward: 'Ward 3',
    phone: '+977-9800000005',
    avatar: 'https://i.pravatar.cc/150?img=15',
  },
];

export const STAFF_DIRECTORY = [
  {
    id: '1',
    name: 'Prakash Kumar KC',
    position: 'Chief Administrative Officer',
    department: 'Administration',
    phone: '+977-9800000010',
    email: 'cao@kachankawal.gov.np',
  },
  {
    id: '2',
    name: 'Saraswati Poudel',
    position: 'Planning Officer',
    department: 'Planning',
    phone: '+977-9800000011',
    email: 'planning@kachankawal.gov.np',
  },
  {
    id: '3',
    name: 'Deepak Adhikari',
    position: 'Revenue Officer',
    department: 'Finance',
    phone: '+977-9800000012',
    email: 'revenue@kachankawal.gov.np',
  },
];

export const WARDS = [
  {
    id: '1',
    number: 1,
    name: 'Ward No. 1',
    area: 'Kachankawal Bazaar Area',
    population: '3,800',
    secretary: 'Govind Prasad Jha',
    phone: '+977-9800000020',
  },
  {
    id: '2',
    number: 2,
    name: 'Ward No. 2',
    area: 'Dharampur Area',
    population: '4,100',
    secretary: 'Bimala Karki',
    phone: '+977-9800000021',
  },
  {
    id: '3',
    number: 3,
    name: 'Ward No. 3',
    area: 'Birtamod Link Area',
    population: '3,950',
    secretary: 'Rajan Yadav',
    phone: '+977-9800000022',
  },
  {
    id: '4',
    number: 4,
    name: 'Ward No. 4',
    area: 'Garamuni Area',
    population: '4,200',
    secretary: 'Sunita Tamang',
    phone: '+977-9800000023',
  },
  {
    id: '5',
    number: 5,
    name: 'Ward No. 5',
    area: 'Gitanagar Area',
    population: '3,600',
    secretary: 'Bishnu Ghimire',
    phone: '+977-9800000024',
  },
  {
    id: '6',
    number: 6,
    name: 'Ward No. 6',
    area: 'Baliya Area',
    population: '4,350',
    secretary: 'Kopila Shrestha',
    phone: '+977-9800000025',
  },
  {
    id: '7',
    number: 7,
    name: 'Ward No. 7',
    area: 'Balubari Area',
    population: '4,000',
    secretary: 'Anish Subedi',
    phone: '+977-9800000026',
  },
];

export const NOTICES = [
  {
    id: '1',
    type: 'notice',
    title: 'Public Meeting — Ward Development Plan 2081/82',
    body: 'All ward citizens are invited to attend the annual development planning meeting. Venue: Municipality Hall. Date: 2081 Falgun 20.',
    date: '2081-12-01',
    isUrgent: false,
    ward: 'All Wards',
  },
  {
    id: '2',
    type: 'tender',
    title: 'Tender Notice — Road Construction Ward 4',
    body: 'Sealed bids are invited from registered contractors for the construction of gravel road in Ward No. 4. Deadline: 2081 Falgun 25.',
    date: '2081-11-28',
    isUrgent: false,
    ward: 'Ward 4',
  },
  {
    id: '3',
    type: 'emergency',
    title: 'ALERT: Flood Warning — Ward 1, 2, 7',
    body: 'Due to heavy rainfall, residents of Ward 1, 2, and 7 near the Mechi River are advised to remain vigilant and move to safe locations.',
    date: '2081-11-25',
    isUrgent: true,
    ward: 'Ward 1, 2, 7',
  },
  {
    id: '4',
    type: 'notice',
    title: 'Tax Collection Drive — Property Tax 2081/82',
    body: 'Property tax collection for fiscal year 2081/82 is underway. Citizens can pay at the municipality office or through authorized collectors.',
    date: '2081-11-20',
    isUrgent: false,
    ward: 'All Wards',
  },
  {
    id: '5',
    type: 'meeting',
    title: 'Ward Committee Meeting — Ward 3',
    body: 'Ward 3 committee meeting scheduled to discuss infrastructure development proposals. All ward members must attend.',
    date: '2081-11-18',
    isUrgent: false,
    ward: 'Ward 3',
  },
];

export const DIGITAL_SERVICES = [
  {
    id: 'birth',
    title: 'Birth Registration',
    icon: 'child-care',
    description: 'Apply for birth certificate for newborns',
    category: 'Vital Registration',
    processingDays: '7-14 working days',
    fee: 'NPR 100',
    requiredDocs: ['Parent citizenship copies', 'Hospital birth record', 'Ward recommendation'],
  },
  {
    id: 'death',
    title: 'Death Registration',
    icon: 'assignment',
    description: 'Register death and obtain death certificate',
    category: 'Vital Registration',
    processingDays: '3-7 working days',
    fee: 'NPR 50',
    requiredDocs: ['Deceased citizenship', 'Hospital death certificate', 'Family member ID'],
  },
  {
    id: 'marriage',
    title: 'Marriage Registration',
    icon: 'favorite',
    description: 'Register marriage and obtain certificate',
    category: 'Vital Registration',
    processingDays: '7-14 working days',
    fee: 'NPR 200',
    requiredDocs: ['Both party citizenships', 'Ward recommendation', 'Witness ID'],
  },
  {
    id: 'migration',
    title: 'Migration Certificate',
    icon: 'swap-horiz',
    description: 'Certificate for change of permanent address',
    category: 'Certificate',
    processingDays: '3-5 working days',
    fee: 'NPR 100',
    requiredDocs: ['Citizenship copy', 'Old ward recommendation', 'Land ownership/rental proof'],
  },
  {
    id: 'recommendation',
    title: 'Recommendation Letter',
    icon: 'description',
    description: 'Official municipal recommendation letters',
    category: 'Certificate',
    processingDays: '1-3 working days',
    fee: 'NPR 50',
    requiredDocs: ['Citizenship copy', 'Application form', 'Purpose documentation'],
  },
  {
    id: 'business',
    title: 'Business Registration',
    icon: 'store',
    description: 'Register business and get operating license',
    category: 'Business',
    processingDays: '7-14 working days',
    fee: 'NPR 500 - 2000',
    requiredDocs: ['Citizenship copy', 'Property/rent agreement', 'Business type documentation'],
  },
];

export const MY_APPLICATIONS = [
  {
    id: 'APP-2081-001',
    service: 'Birth Registration',
    applicant: 'Rajesh Gurung',
    date: '2081-11-15',
    status: 'approved',
    statusLabel: 'Approved',
    ward: 'Ward 2',
  },
  {
    id: 'APP-2081-002',
    service: 'Recommendation Letter',
    applicant: 'Rajesh Gurung',
    date: '2081-12-01',
    status: 'processing',
    statusLabel: 'In Process',
    ward: 'Ward 2',
  },
];

export const COMPLAINTS = [
  {
    id: 'CMP-2081-001',
    category: 'Road & Infrastructure',
    title: 'Pothole on main road near Ward 3',
    description: 'Large pothole on the main road near Birtamod link causing accidents.',
    date: '2081-11-20',
    status: 'resolved',
    statusLabel: 'Resolved',
    ward: 'Ward 3',
  },
  {
    id: 'CMP-2081-002',
    category: 'Water Supply',
    title: 'No water supply for 3 days in Ward 5',
    description: 'Ward 5 residents have not received water for 3 consecutive days.',
    date: '2081-12-02',
    status: 'processing',
    statusLabel: 'In Review',
    ward: 'Ward 5',
  },
];

export const COMPLAINT_CATEGORIES = [
  'Road & Infrastructure',
  'Water Supply',
  'Electricity',
  'Waste Management',
  'Public Spaces',
  'Health Services',
  'Education',
  'Land & Property',
  'Other',
];

export const HEALTH_FACILITIES = [
  {
    id: '1',
    name: 'Kachankawal Health Post',
    type: 'Health Post',
    ward: 'Ward 1',
    phone: '+977-023-540XXX',
    address: 'Kachankawal Bazaar',
    services: ['OPD', 'Maternal Health', 'Vaccination', 'Emergency First Aid'],
    openHours: 'Sun–Fri: 9am–4pm',
  },
  {
    id: '2',
    name: 'Dharampur Sub-Health Post',
    type: 'Sub Health Post',
    ward: 'Ward 2',
    phone: '+977-023-541XXX',
    address: 'Dharampur, Ward 2',
    services: ['OPD', 'Family Planning', 'Child Health'],
    openHours: 'Sun–Fri: 9am–3pm',
  },
  {
    id: '3',
    name: 'Jhapa District Hospital',
    type: 'District Hospital',
    ward: 'Birtamod (Nearby)',
    phone: '+977-023-540001',
    address: 'Birtamod, Jhapa',
    services: ['Emergency', 'Surgery', 'ICU', 'Laboratory'],
    openHours: '24/7',
  },
];

export const SCHOOLS = [
  {
    id: '1',
    name: 'Shree Kachankawal Secondary School',
    type: 'Secondary',
    ward: 'Ward 1',
    grade: 'Grade 1–12',
    phone: '+977-023-542XXX',
  },
  {
    id: '2',
    name: 'Shree Dharampur Primary School',
    type: 'Primary',
    ward: 'Ward 2',
    grade: 'Grade 1–5',
    phone: '+977-023-543XXX',
  },
  {
    id: '3',
    name: 'Garamuni Secondary School',
    type: 'Secondary',
    ward: 'Ward 4',
    grade: 'Grade 1–10',
    phone: '+977-023-544XXX',
  },
];

export const EMERGENCY_CONTACTS = [
  {
    id: '1',
    name: 'Police (Emergency)',
    number: '100',
    type: 'police',
    icon: 'local-police',
    description: 'Nepal Police Emergency Helpline',
  },
  {
    id: '2',
    name: 'Ambulance',
    number: '102',
    type: 'ambulance',
    icon: 'local-hospital',
    description: 'Emergency Ambulance Service',
  },
  {
    id: '3',
    name: 'Fire Brigade',
    number: '101',
    type: 'fire',
    icon: 'local-fire-department',
    description: 'Fire Emergency Service',
  },
  {
    id: '4',
    name: 'Municipality Office',
    number: '+977-023-540XXX',
    type: 'municipality',
    icon: 'account-balance',
    description: 'Municipal Administration Office',
  },
  {
    id: '5',
    name: 'Disaster Relief',
    number: '1155',
    type: 'disaster',
    icon: 'warning',
    description: 'National Disaster Relief Hotline',
  },
];

export const EVENTS = [
  {
    id: '1',
    title: 'Farmer Cooperative Training',
    category: 'Agriculture',
    date: '2081 Falgun 22',
    time: '10:00 AM',
    venue: 'Municipality Hall',
    description: 'Training program on organic farming techniques for local farmers.',
    ward: 'All Wards',
    organizer: 'Agriculture Department',
  },
  {
    id: '2',
    title: 'Women Empowerment Awareness',
    category: 'Social',
    date: '2081 Falgun 25',
    time: '9:00 AM',
    venue: 'Community Center, Ward 3',
    description: 'Awareness campaign on women rights, health, and economic empowerment.',
    ward: 'Ward 3, 4, 5',
    organizer: 'Social Development Dept.',
  },
  {
    id: '3',
    title: 'Vaccination Drive 2081',
    category: 'Health',
    date: '2081 Chaitra 1',
    time: '8:00 AM',
    venue: 'All Health Posts',
    description: 'Annual children vaccination drive covering all 7 wards.',
    ward: 'All Wards',
    organizer: 'Health Section',
  },
];
